// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import ApplyFilterController from "./apply_filter_controller"
application.register("apply-filter", ApplyFilterController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import NewPostFormController from "./new_post_form_controller"
application.register("new-post-form", NewPostFormController)

import PhotoCropperController from "./photo_cropper_controller"
application.register("photo-cropper", PhotoCropperController)

import PhotoFilterController from "./photo_filter_controller"
application.register("photo-filter", PhotoFilterController)
